### ISSUE TITLE
TypeError: Cannot read property 'history' of undefined

### ISSUE THREAD

**Issue by gihanrcg** [hansfpc/react-private-route#10]
```
<PrivateRoute
     path="/admin"
     component={AdminPanel}
     isAuthenticated={userType==='Admin'}
/>
```
TypeError: Cannot read property 'history' of undefined
e.render
D:/Private/AF/final_project/client/node_modules/react-private-route/lib/index.js:636
  633 | o = e.component,
  634 | r = e.render,
  635 | i = this.context.router,
  636 | a = i.history,
  637 | c = i.route,
  638 | u = i.staticContext,
  639 | s = this.props.location || c.location,

**Comment by hansfpc** [comment]
Suppose you have some root component called MyApp. You need to make its root node to be a router (ex: BrowserRouter) that will react on url changes and provide PrivateRoute with correct router implementation via context.

**Comment by hansfpc** [comment]
@gihanrcg  have you solved your problem?

**Comment by elja** [comment]
Hey, I'm using connected router that wraps PrivateRoute component and getting the same error, can you maybe help me there?

**Comment by guizmo** [comment]
I had the same issue
fixed it by creating my own component with the exact code from [https://github.com/hansfpc/react-private-route/blob/master/src/components/PrivateRoute.js](PrivateRoute).

So maybe it is a dependencie issue on Redirect from react-router-dom...

**Comment by bpAhmadi3d** [comment]
Same issue, i fixed it by copying the PrivateRoute code and creating my own PrivateRoute as guizmo suggested, i hope you can fix this issue, thx.

**Comment by burnedikt** [comment]
Same issue here. This package depends on `react-router-dom` `^4.3.1`. If you're using a different version (experienced with `^5.2.0`, you will get the error mentioned above.
